### ISSUE TITLE
How Can I run the demo?

### ISSUE THREAD

**Issue by rakesh-roshan** [ltearno/gwtcon-jsr269#1]

**Comment by ltearno** [comment]
There was an error in the pom.xml, so I added a commit to fix it. Update the project and run a `mvn clean install`, everything should work.

Now, if you use Eclipse, you need to be sure to have `m2e-apt` installed in it (really easy to do from the Eclipse Marketplace). It is part of the Maven 2 Eclipse plugin, but this specific part has to be installed...
Then you can import the `auto-ui-builder-demo` into Eclipse, and everything should work fine.

Now to run the project, go in the `auto-ui-builder-demo` directory and launch `mvn gwt:run`.

You can access the demo from your browser by going to `http://localhost:8888`

Let me know if you encounter problems...

**Comment by ltearno** [comment]
Is that working?

**Comment by rakesh-roshan** [comment]
Yeah it worked. Thanks a lot. It is really helpful in my project.
